universe                = vanilla
executable              = wrapper_axes.sh
arguments               = $(args)
output                  = condor/logs_axes/$(Cluster).$(Process).out
error                   = condor/logs_axes/$(Cluster).$(Process).err
log                     = condor/logs_axes/$(Cluster).log
request_cpus            = 1
request_memory          = 4096
should_transfer_files   = NO
getenv                  = False
+UseOS                  = "el9"
+JobCategory            = "medium"
queue args from jobs_axes.txt
