universe                = vanilla
executable              = wrapper.sh
arguments               = $(args)
output                  = condor/logs/$(Cluster).$(Process).out
error                   = condor/logs/$(Cluster).$(Process).err
log                     = condor/logs/$(Cluster).log
request_cpus            = 1
request_memory          = 3072
should_transfer_files   = NO
getenv                  = False
+UseOS                  = "el9"
+JobCategory            = "medium"
queue args from canary_jobs.txt
